#!/bin/bash

docker run \
  --rm \
  --name rebase-labs \
  -w /app \
  -v $(pwd):/app \
  -v rebase_gems:/usr/local/bundle/ \
  -p 3000:3000 \
  --network newone \
  ruby \
  bash -c "bundle install && ruby server.rb"